(()=>{
  'use strict';
  const root=document.getElementById('fb-ad-manager-alpha-v20');
  if(!root||root.dataset.interactionV20)return; root.dataset.interactionV20='1';
  const $=s=>root.querySelector(s),tracker=$('#fb-ad-alpha-tracker'); if(!tracker)return;
  const css=document.createElement('style');css.textContent=`
#fb-ad-manager-alpha-v20 .header-actions{display:flex;gap:3px;align-items:center}#fb-ad-manager-alpha-v20 .minimize{border:0;background:transparent;color:#fff;padding:2px 7px;font-size:21px;line-height:1}#fb-ad-manager-alpha-v20 .mini-status{display:none;max-width:220px;margin-top:4px;color:#d9ebff;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#fb-ad-manager-alpha-v20.minimized{width:min(330px,calc(100vw - 28px))}#fb-ad-manager-alpha-v20.minimized main{display:none}#fb-ad-manager-alpha-v20.minimized .tag{display:none}#fb-ad-manager-alpha-v20.minimized .mini-status{display:block}#fb-ad-manager-alpha-v20 .tracker .action-choices{display:grid;grid-template-columns:1fr 1fr;gap:8px}#fb-ad-manager-alpha-v20 .tracker .action-choices button{margin:0;padding:10px;background:#172238;color:#d7e8fa;border:1px solid #426b94}#fb-ad-manager-alpha-v20 .tracker .action-choices button.selected{background:#1264ad;color:#fff;border-color:#65c4ff;box-shadow:inset 3px 0 #75d2ff}#fb-ad-manager-alpha-v20 .tracker .two-col{display:grid;grid-template-columns:1fr 1fr;gap:8px}#fb-ad-manager-alpha-v20 .tracker .hint{margin-top:10px;padding:9px;border-left:3px solid #47b9fb;background:#11233a;color:#d7e8fa;font-size:11px;line-height:1.5}#fb-ad-manager-alpha-v20 .tracker .current{outline:2px solid #59c1ff;outline-offset:2px;border-radius:8px}#fb-ad-manager-alpha-v20 .tracker .result strong{display:block;color:#fff;margin-bottom:4px}`;root.append(css);
  const header=$('header'),close=$('.close'),headActions=document.createElement('div');headActions.className='header-actions';const mini=document.createElement('button');mini.className='minimize';mini.type='button';mini.textContent='−';mini.title='最小化';mini.setAttribute('aria-label','最小化');if(close){close.replaceWith(headActions);headActions.append(mini,close)}else header.append(headActions);const headText=header.querySelector('div');const miniStatus=document.createElement('span');miniStatus.className='mini-status';miniStatus.textContent='面板已最小化';headText?.append(miniStatus);mini.onclick=()=>{const small=root.classList.toggle('minimized');mini.textContent=small?'□':'−';mini.title=small?'還原':'最小化';if(small)miniStatus.textContent=$('#fb-ad-alpha-track-status')?.textContent||'面板已最小化'};
  tracker.innerHTML=`<label for="fb-ad-alpha-keyword">搜尋關鍵字</label><input id="fb-ad-alpha-keyword" type="text" placeholder="多組可用逗號或換行；任一符合即列入"><label>預備動作（可複選）</label><div class="action-choices"><button type="button" data-action="heart" aria-pressed="false">愛心</button><button type="button" data-action="comment" aria-pressed="false">留言</button></div><div id="fb-ad-alpha-comment-fields" hidden><label for="fb-ad-alpha-message">預備留言</label><textarea id="fb-ad-alpha-message" placeholder="執行本則時填入 Facebook 留言框；送出前由你確認"></textarea></div><div class="two-col"><div><label for="fb-ad-alpha-rounds">最多滑動次數</label><input id="fb-ad-alpha-rounds" type="number" min="0" max="50" value="5"></div><div><label for="fb-ad-alpha-limit">本輪候選上限</label><input id="fb-ad-alpha-limit" type="number" min="1" max="20" value="20"></div></div><div class="hint">建議最多 20 則。快捷鍵：E 執行、S 完成本則、D／F 上下切換、X 略過。愛心會直接按下；留言只填入原生留言框，最後送出仍由你確認。</div><div class="row" style="margin-top:10px"><button class="secondary" id="fb-ad-alpha-scan">開始掃描</button><button class="secondary" id="fb-ad-alpha-stop" disabled>停止</button></div><div class="status" id="fb-ad-alpha-track-status">先選擇愛心或留言，再掃描中央動態牆。</div><div class="results" id="fb-ad-alpha-results"></div>`;
  const keyword=$('#fb-ad-alpha-keyword'),message=$('#fb-ad-alpha-message'),rounds=$('#fb-ad-alpha-rounds'),limit=$('#fb-ad-alpha-limit'),scan=$('#fb-ad-alpha-scan'),stop=$('#fb-ad-alpha-stop'),status=$('#fb-ad-alpha-track-status'),results=$('#fb-ad-alpha-results'),commentFields=$('#fb-ad-alpha-comment-fields'),selected=new Set(),handled=new Set();let queue=[],index=-1,stopped=false;
  const say=(text,kind='')=>{status.textContent=text;status.className='status '+kind;if(root.classList.contains('minimized'))miniStatus.textContent=text},clean=v=>String(v||'').replace(/\s+/g,' ').trim(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),visible=el=>{const r=el?.getBoundingClientRect?.();return !!(r&&r.width>0&&r.height>0&&getComputedStyle(el).visibility!=='hidden')},inFeed=el=>!el.closest?.('nav,aside,[role="navigation"],[role="complementary"]')&&!!el.closest?.('[role="main"]'),terms=()=>[...new Set(keyword.value.split(/[，,\n;；]+/).map(x=>x.trim()).filter(Boolean))].slice(0,12),keyOf=t=>clean(t).slice(0,240);
  const closestPost=node=>{for(let cur=node;cur&&cur!==document.body;cur=cur.parentElement)if(cur.matches?.('article,[role="article"],[data-pagelet^="FeedUnit_"]')||cur.hasAttribute?.('aria-posinset'))return cur;return node};
  const findPosts=words=>{const found=[],seen=new Set(),add=el=>{if(!el||root.contains(el)||!visible(el)||!inFeed(el))return;const text=clean(el.innerText),matched=words.filter(w=>text.includes(w)),key=keyOf(text);if(!matched.length||seen.has(key)||handled.has(key))return;seen.add(key);found.push({el,text,key,matched})};document.querySelectorAll('article,[role="article"],[data-pagelet^="FeedUnit_"]').forEach(add);if(!found.length){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode())&&found.length<40){const h=n.parentElement;if(h&&visible(h)&&inFeed(h))add(closestPost(h))}}return found};
  const nativeLabel=el=>clean([el?.getAttribute?.('aria-label'),el?.getAttribute?.('title'),el?.innerText,el?.textContent,...[...(el?.querySelectorAll?.('[aria-label],[title]')||[])].flatMap(x=>[x.getAttribute('aria-label'),x.getAttribute('title')])].filter(Boolean).join(' '));
  const nativeAction=(item,type)=>{const re=type==='heart'?/讚|like/i:/留言|回覆|comment|reply/i,nodes=[...item.el.querySelectorAll('button,[role="button"],[aria-label],[title]')].filter(visible),hit=nodes.find(el=>re.test(nativeLabel(el)));return hit?.closest('button,[role="button"],a,[tabindex="0"]')||hit||null};
  const fill=(editor,text)=>{editor.focus();if(editor.isContentEditable){editor.textContent=text;editor.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}))}else{const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set||Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(editor,text);editor.dispatchEvent(new Event('input',{bubbles:true}));editor.dispatchEvent(new Event('change',{bubbles:true}))}};
  const focus=next=>{if(!queue.length)return;index=Math.max(0,Math.min(queue.length-1,next));[...results.children].forEach(x=>x.classList.remove('current'));const item=queue[index];item.el.scrollIntoView({behavior:'smooth',block:'center'});item.el.style.outline='3px solid #38bdf8';setTimeout(()=>item.el.style.outline='',2500);results.children[index]?.classList.add('current');say('目前第 '+(index+1)+'／'+queue.length+' 則。按 E 執行，或 X 略過。','ok')};
  const advance=done=>{if(done&&queue[index])handled.add(queue[index].key);if(index>=queue.length-1){index=queue.length;say('本輪 '+queue.length+' 則候選已完成。','ok');return}focus(index+1)};
  const execute=async()=>{const item=queue[index];if(!item)return;say('正在處理第 '+(index+1)+' 則…');item.el.scrollIntoView({behavior:'smooth',block:'center'});await sleep(250);const done=[];if(selected.has('heart')){const heart=nativeAction(item,'heart');if(!heart){say('這一則找不到 Facebook 原生讚按鈕，請人工確認或按 X 略過。','bad');return}if(!/收回讚|unlike/i.test(nativeLabel(heart))){heart.click();done.push('已按愛心')}else done.push('已有愛心')}if(selected.has('comment')){const comment=nativeAction(item,'comment');if(!comment){say((done.join('、')||'')+'，但找不到 Facebook 留言按鈕。','bad');return}comment.click();let editor=null;for(let i=0;i<20&&!editor;i++){await sleep(220);const candidates=[...document.querySelectorAll('textarea,input[type="text"],[contenteditable="true"],[role="textbox"]')].filter(el=>!root.contains(el)&&visible(el));editor=(document.activeElement&&!root.contains(document.activeElement)&&document.activeElement.matches?.('textarea,input[type="text"],[contenteditable="true"],[role="textbox"]')?document.activeElement:null)||candidates.find(el=>item.el.contains(el))||candidates.find(el=>/留言|回覆|comment|reply/i.test(nativeLabel(el)))||null}if(!editor){say((done.join('、')||'')+'，但留言框尚未出現；請人工點開後再按 E。','bad');return}fill(editor,message.value.trim());done.push('留言已填入')}if(selected.has('comment'))say(done.join('、')+'；請確認 Facebook 原生送出後，再按 S 完成本則。','ok');else{say(done.join('、')+'；正在前往下一則。','ok');advance(true)}};
  const render=items=>{queue=items;index=-1;results.innerHTML='';if(!items.length){say('本輪沒有找到符合關鍵字的貼文。','bad');return}items.forEach((item,n)=>{const row=document.createElement('div');row.className='result';const title=document.createElement('strong');title.textContent=(n+1)+'. 命中：'+item.matched.join('／');const preview=document.createElement('div');preview.textContent=item.text.length>130?item.text.slice(0,130)+'…':item.text;const locate=document.createElement('button');locate.textContent='定位本則';locate.onclick=()=>focus(n);const run=document.createElement('button');run.textContent='執行（E）';run.onclick=()=>{focus(n);execute()};const skip=document.createElement('button');skip.textContent='略過（X）';skip.onclick=()=>{focus(n);advance(true)};row.append(title,preview,locate,run,skip);results.append(row)});focus(0)};
  [...tracker.querySelectorAll('[data-action]')].forEach(button=>button.onclick=()=>{const action=button.dataset.action;selected.has(action)?selected.delete(action):selected.add(action);button.classList.toggle('selected',selected.has(action));button.setAttribute('aria-pressed',String(selected.has(action)));commentFields.hidden=!selected.has('comment');say(selected.size?'已選：'+[...selected].map(x=>x==='heart'?'愛心':'留言').join('＋')+'。':'請至少選一個動作。',selected.size?'ok':'bad')});
  scan.onclick=async()=>{const words=terms();if(!selected.size){say('請先複選愛心或留言。','bad');return}if(!words.length){say('請輸入至少一個搜尋關鍵字。','bad');keyword.focus();return}if(selected.has('comment')&&!message.value.trim()){say('選擇留言後，請先輸入預備留言。','bad');message.focus();return}const max=Math.min(50,Math.max(0,parseInt(rounds.value,10)||0)),cap=Math.min(20,Math.max(1,parseInt(limit.value,10)||20)),all=new Map();stopped=false;scan.disabled=true;stop.disabled=false;results.innerHTML='';for(let round=0;round<=max&&!stopped&&all.size<cap;round++){for(const item of findPosts(words)){if(all.size>=cap)break;all.set(item.key,item)}say('搜尋第 '+(round+1)+' 輪：目前找到 '+all.size+'／'+cap+' 則。');if(round<max&&all.size<cap){window.scrollBy(0,Math.max(500,Math.floor(innerHeight*.78)));await sleep(1100)}}scan.disabled=false;stop.disabled=true;render([...all.values()])};stop.onclick=()=>{stopped=true;say('已要求停止，會在本輪搜尋後結束。')};
  document.addEventListener('keydown',event=>{if(!root.isConnected||tracker.hidden||!queue.length||index<0||index>=queue.length||event.ctrlKey||event.metaKey||event.altKey||event.target?.matches?.('input,textarea,[contenteditable="true"]'))return;const key=event.key.toLowerCase();if(!'esdfx'.includes(key))return;event.preventDefault();if(key==='e')execute();else if(key==='s')advance(true);else if(key==='d')focus(index-1);else if(key==='f')focus(index+1);else advance(true)});
})();
