(()=>{
  'use strict';
  const ID='fb-ad-alpha-local-scheduler';
  if(document.getElementById(ID))return;
  const platform=/threads\.net/i.test(location.hostname)?'threads':/instagram\.com/i.test(location.hostname)?'instagram':'';
  const root=document.createElement('section');root.id=ID;
  root.innerHTML=`<style>
#${ID}{position:fixed;z-index:2147483647;right:18px;top:74px;width:min(395px,calc(100vw - 26px));font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif;color:#eff6ff}#${ID}*{box-sizing:border-box}#${ID} .box{overflow:hidden;border:1px solid #365783;border-radius:18px;background:#0c172b;box-shadow:0 22px 65px #000a}#${ID} header{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;background:linear-gradient(90deg,#312e81,#0e7490);cursor:grab;user-select:none}#${ID} h1{font-size:16px;margin:0}#${ID} .tag{font-size:11px;color:#ccfbf1}#${ID} main{padding:15px}#${ID} p,#${ID} .hint{font-size:12px;line-height:1.55;color:#bfd0e9}#${ID} label{display:block;margin:11px 0 6px;font-size:13px;font-weight:750}#${ID} textarea,#${ID} input,#${ID} select{width:100%;border:1px solid #496b97;border-radius:9px;padding:10px;background:#081120;color:#fff;font:14px inherit}#${ID} textarea{min-height:88px;resize:vertical}#${ID} .row{display:flex;gap:8px}#${ID} .row>*{flex:1}#${ID} button{border:0;border-radius:9px;padding:9px 11px;font:700 13px inherit;cursor:pointer;background:#1e3a5f;color:#eaf5ff}#${ID} button.primary{background:#38bdf8;color:#06203a}#${ID} button.danger{background:#9f1239;color:#fff}#${ID} button.close{padding:2px 8px;background:transparent;font-size:22px;color:#fff}#${ID} button:disabled{opacity:.48;cursor:not-allowed}#${ID} .preview{margin-top:10px;max-height:120px;overflow:auto;padding:10px;border:1px solid #27496e;border-radius:9px;background:#07101e;white-space:pre-wrap;font-size:12px;color:#dbeafe}#${ID} .state{margin-top:10px;min-height:20px;font-size:12px;color:#a9bedb}#${ID} .ok{color:#86efac}.bad{color:#fca5a5}#${ID} .schedule{margin-top:12px;padding:11px;border:1px solid #31517e;border-radius:12px;background:#0a1527}#${ID} .minor{font-size:11px;color:#94a9c9;margin-top:8px}
</style><div class="box"><header><div><h1>33 廣告管理助手</h1><span class="tag">Threads／IG 本機草稿排程 · alpha</span></div><button class="close" aria-label="關閉">×</button></header><main>
<p>在目前平台的原生發文視窗完成文字與照片，再由這個面板保留倒數並於時間到點按「發佈／分享」。電腦、瀏覽器與此目標分頁必須持續開啟。</p>
<label>目前目標平台</label><select id="s-platform"><option value="">請在 Threads 或 Instagram 分頁啟動</option><option value="threads">Threads</option><option value="instagram">Instagram</option></select>
<label for="s-draft">草稿文字（用於預覽與核對）</label><textarea id="s-draft" placeholder="請貼入你已放進平台發文框的文字；不會自動替你填入或上傳照片。"></textarea><div class="preview" id="s-preview">尚未填入草稿預覽。</div>
<div class="schedule"><label for="s-time">送出時間（本機時間）</label><input id="s-time" type="datetime-local"><div class="row" style="margin-top:10px"><button id="s-check">檢查發文視窗</button><button class="primary" id="s-start">開始倒數</button></div><div class="row" style="margin-top:8px"><button class="danger" id="s-cancel" disabled>取消排程</button><button id="s-now">立即測試送出</button></div><div class="state" id="s-state">尚未排程。</div><div class="minor">到點若找不到唯一且可見的發佈按鈕，系統不會亂點，會保留草稿並顯示原因。</div></div>
</main></div>`;
  document.documentElement.append(root);const $=s=>root.querySelector(s),sel=$('#s-platform'),draft=$('#s-draft'),preview=$('#s-preview'),time=$('#s-time'),state=$('#s-state'),start=$('#s-start'),cancel=$('#s-cancel');sel.value=platform;
  let timer=null,scheduledAt=0,drag=null;
  const say=(text,kind='')=>{state.className='state '+kind;state.textContent=text};
  const visible=el=>{const r=el?.getBoundingClientRect?.();return !!r&&r.width>2&&r.height>2&&getComputedStyle(el).visibility!=='hidden'};
  const normalize=s=>String(s||'').replace(/\s+/g,' ').trim();
  const buttons=()=>[...document.querySelectorAll('button,[role="button"],div[tabindex="0"]')].filter(el=>!root.contains(el)&&visible(el));
  function findComposer(){const p=sel.value;const editable=[...document.querySelectorAll('[contenteditable="true"],textarea')].filter(el=>!root.contains(el)&&visible(el));return editable.find(el=>{const text=normalize(el.getAttribute('aria-label')||el.getAttribute('placeholder')||'');return p==='threads'?/thread|發文|內容|開始/.test(text)||true:p==='instagram'?/caption|說明|撰寫|write/.test(text)||true:false})||editable[0]||null}
  function findSubmit(){const p=sel.value;const labels=p==='threads'?['發佈','發布','Post']:p==='instagram'?['分享','Share']:[];const found=buttons().filter(el=>labels.includes(normalize(el.innerText||el.getAttribute('aria-label'))));return found.length===1?found[0]:null}
  function inspect(){if(!sel.value){say('請先在 Threads 或 Instagram 的目標分頁啟動面板。','bad');return false}const composer=findComposer(),submit=findSubmit();if(!composer){say('找不到可見的原生發文框。請先完成草稿與照片選取。','bad');return false}if(!submit){say('已找到發文框，但目前找不到唯一可送出的「發佈／分享」按鈕；請確認草稿完整。','bad');return false}say('檢查完成：已找到原生發文框與唯一送出按鈕。','ok');return true}
  function send(){if(!inspect())return false;const submit=findSubmit();try{submit.click();say('已在 '+new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',second:'2-digit'})+' 點擊原生送出按鈕；請在平台畫面確認是否發佈成功。','ok');return true}catch{say('送出按鈕無法點擊，草稿已保留。','bad');return false}}
  function stop(note='已取消排程，平台原生草稿仍保留。'){if(timer)clearTimeout(timer);timer=null;scheduledAt=0;cancel.disabled=true;start.disabled=false;say(note)}
  function tick(){const remain=scheduledAt-Date.now();if(remain<=0){timer=null;cancel.disabled=true;start.disabled=false;send();return}const sec=Math.ceil(remain/1000),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;say('已排程，倒數 '+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'。請保持本分頁開啟。','ok');timer=setTimeout(tick,Math.min(1000,remain))}
  draft.oninput=()=>preview.textContent=draft.value.trim()||'尚未填入草稿預覽。';
  $('#s-check').onclick=inspect;$('#s-now').onclick=()=>{if(confirm('會立刻點擊平台的原生發佈／分享按鈕。確定要測試送出嗎？'))send()};
  start.onclick=()=>{const at=new Date(time.value).getTime();if(!Number.isFinite(at)||at<=Date.now()){say('請選擇晚於現在的送出時間。','bad');time.focus();return}if(!draft.value.trim()){say('請貼入草稿文字，讓你在倒數期間能核對內容。','bad');draft.focus();return}if(!inspect())return;scheduledAt=at;cancel.disabled=false;start.disabled=true;tick()};cancel.onclick=()=>stop();$('.close').onclick=()=>{if(timer&&!confirm('目前仍在倒數，關閉等同取消排程。確定關閉？'))return;stop();root.remove()};
  const header=$('header');header.onpointerdown=e=>{if(e.target.closest('button'))return;const r=root.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX-r.left,y:e.clientY-r.top};root.style.left=r.left+'px';root.style.top=r.top+'px';root.style.right='auto'};header.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;root.style.left=Math.max(0,Math.min(innerWidth-root.offsetWidth,e.clientX-drag.x))+'px';root.style.top=Math.max(0,Math.min(innerHeight-root.offsetHeight,e.clientY-drag.y))+'px'};header.onpointerup=header.onpointercancel=()=>drag=null;
})();
